 local menue0e4fc6213e8b3593495a7260c3a4c2e = {
     {"Accerciser", "accerciser", "/usr/share/icons/hicolor/16x16/apps/accerciser.png" },
     {"KMag", "kmag", "/usr/share/icons/hicolor/16x16/apps/kmag.png" },
     {"KMouseTool", "kmousetool -qwindowtitle KMouseTool", "/usr/share/icons/hicolor/16x16/apps/kmousetool.png" },
     {"KMouth", "kmouth", "/usr/share/icons/hicolor/16x16/apps/kmouth.png" },
 }

 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"Archive Manager", "file-roller "},
     {"Ark", "ark ", "/usr/share/icons/hicolor/48x48/apps/ark.png" },
     {"Calculator", "gnome-calculator"},
     {"Characters", "/usr/bin/gnome-characters"},
     {"ClipIt", "clipit"},
     {"Clocks", "gnome-clocks"},
     {"CopyQ", "copyq", "/usr/share/icons/hicolor/16x16/apps/copyq.png" },
     {"Disks", "gnome-disks"},
     {"Filelight", "filelight ", "/usr/share/icons/hicolor/16x16/apps/filelight.png" },
     {"Files", "nautilus --new-window "},
     {"Fonts", "gnome-font-viewer "},
     {"KBackup", "kbackup ", "/usr/share/icons/hicolor/16x16/apps/kbackup.png" },
     {"KCalc", "kcalc"},
     {"KCharSelect", "kcharselect --qwindowtitle KCharSelect"},
     {"KFloppy", "kfloppy -qwindowtitle KFloppy", "/usr/share/icons/hicolor/16x16/apps/kfloppy.png" },
     {"KMag", "kmag", "/usr/share/icons/hicolor/16x16/apps/kmag.png" },
     {"KMail Import Wizard", "akonadiimportwizard", "/usr/share/icons/hicolor/64x64/apps/kontact-import-wizard.png" },
     {"KMouseTool", "kmousetool -qwindowtitle KMouseTool", "/usr/share/icons/hicolor/16x16/apps/kmousetool.png" },
     {"KMouth", "kmouth", "/usr/share/icons/hicolor/16x16/apps/kmouth.png" },
     {"KRename", "krename -qwindowtitle \"KRename\"  ", "/usr/share/icons/hicolor/32x32/apps/krename.png" },
     {"KTeaTime", "kteatime", "/usr/share/icons/hicolor/16x16/apps/kteatime.png" },
     {"KTimer", "ktimer", "/usr/share/icons/hicolor/16x16/apps/ktimer.png" },
     {"KWrite", "kwrite ", "/usr/share/icons/hicolor/16x16/apps/kwrite.png" },
     {"Kate", "kate -b ", "/usr/share/icons/hicolor/16x16/apps/kate.png" },
     {"Kleopatra", "kleopatra", "/usr/share/icons/hicolor/16x16/apps/kleopatra.png" },
     {"Klipper", "klipper"},
     {"Krusader", "krusader -qwindowtitle Krusader ", "/usr/share/icons/hicolor/16x16/apps/krusader_user.png" },
     {"Kvantum Manager", "kvantummanager"},
     {"Maps", "gapplication launch org.gnome.Maps "},
     {"Neovim", "xterm -e nvim ", "/usr/share/pixmaps/nvim.png" },
     {"Passwords and Keys", "seahorse"},
     {"Recipes", "gnome-recipes ", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Recipes.png" },
     {"Screenshot", "gnome-screenshot --interactive"},
     {"Spectacle", "/usr/bin/spectacle", "/usr/share/icons/hicolor/16x16/apps/spectacle.png" },
     {"Sweeper", "sweeper"},
     {"Text Editor", "gedit "},
     {"To Do", "gnome-todo", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Todo.png" },
     {"Vim", "xterm -e vim ", "/usr/share/icons/hicolor/48x48/apps/gvim.png" },
     {"Weather", "gapplication launch org.gnome.Weather"},
     {"Winetricks", "winetricks --gui"},
     {"compton", "compton", "/usr/share/icons/hicolor/48x48/apps/compton.png" },
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
     {"nitrogen", "nitrogen", "/usr/share/icons/hicolor/16x16/apps/nitrogen.png" },
     {"picom", "picom"},
     {"xgps", "xgps", "///usr/share/gpsd/gpsd-logo.png" },
     {"xgpsspeed", "xgpsspeed", "///usr/share/gpsd/gpsd-logo.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"Artikulate", "artikulate -qwindowtitle \"Artikulate\" ", "/usr/share/icons/hicolor/16x16/apps/artikulate.png" },
     {"Blinken", "blinken", "/usr/share/icons/hicolor/16x16/apps/blinken.png" },
     {"Cantor", "cantor -qwindowicon cantor -qwindowtitle Cantor ", "/usr/share/icons/hicolor/16x16/apps/cantor.png" },
     {"GNU Octave", "/usr/bin/octave --gui ", "/usr/share/icons/hicolor/16x16/apps/octave.png" },
     {"KAlgebra", "kalgebra ", "/usr/share/icons/hicolor/64x64/apps/kalgebra.png" },
     {"KAlgebra Mobile", "kalgebramobile ", "/usr/share/icons/hicolor/64x64/apps/kalgebra.png" },
     {"KBruch", "kbruch -qwindowtitle KBruch -qwindowicon kbruch", "/usr/share/icons/hicolor/16x16/apps/kbruch.png" },
     {"KDE Marble", "marble ", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"KGeography", "kgeography", "/usr/share/icons/hicolor/16x16/apps/kgeography.png" },
     {"KHangMan", "khangman -qwindowtitle \"KHangMan\" ", "/usr/share/icons/hicolor/16x16/apps/khangman.png" },
     {"KLettres", "klettres -qwindowtitle KLettres -qwindowicon klettres", "/usr/share/icons/hicolor/16x16/apps/klettres.png" },
     {"KTouch", "ktouch", "/usr/share/icons/hicolor/16x16/apps/ktouch.png" },
     {"KTurtle", "kturtle -qwindowtitle KTurtle", "/usr/share/icons/hicolor/16x16/apps/kturtle.png" },
     {"KWordQuiz", "kwordquiz  -qwindowtitle KWordQuiz -qwindowicon kwordquiz", "/usr/share/icons/hicolor/16x16/apps/kwordquiz.png" },
     {"Kalzium", "kalzium -qwindowtitle Kalzium", "/usr/share/icons/hicolor/16x16/apps/kalzium.png" },
     {"Kanagram", "kanagram", "/usr/share/icons/hicolor/16x16/apps/kanagram.png" },
     {"Kig", "kig  --qwindowtitle Kig", "/usr/share/icons/hicolor/16x16/apps/kig.png" },
     {"Kiten", "kiten -qwindowtitle Kiten -qwindowicon kiten", "/usr/share/icons/hicolor/16x16/apps/kiten.png" },
     {"KmPlot", "kmplot ", "/usr/share/icons/hicolor/16x16/apps/kmplot.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"Minuet", "minuet", "/usr/share/icons/hicolor/16x16/apps/minuet.png" },
     {"Parley", "parley ", "/usr/share/icons/hicolor/16x16/apps/parley.png" },
     {"R", "xterm -e R", "///usr/share/pixmaps/r.png" },
     {"Rocs", "rocs  -qwindowtitle Rocs", "/usr/share/icons/hicolor/16x16/apps/rocs.png" },
     {"Singular", "xterm -e Singular", "///usr/share/icons/Singular.png" },
     {"Step", "step -qwindowtitle Step -qwindowicon step", "/usr/share/icons/hicolor/16x16/apps/step.png" },
     {"xmaxima", "xmaxima", "/usr/share/pixmaps/net.sourceforge.maxima.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"Blinken", "blinken", "/usr/share/icons/hicolor/16x16/apps/blinken.png" },
     {"Bomber", "bomber -qwindowtitle Bomber", "/usr/share/icons/hicolor/32x32/apps/bomber.png" },
     {"Bovo", "bovo -qwindowtitle Bovo", "/usr/share/icons/hicolor/16x16/apps/bovo.png" },
     {"Chess", "gnome-chess"},
     {"Dosbox", "dosbox", "/usr/share/pixmaps/dosbox.png" },
     {"Five or More", "five-or-more", "/usr/share/icons/hicolor/16x16/apps/org.gnome.five-or-more.png" },
     {"Four-in-a-row", "four-in-a-row", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Four-in-a-row.png" },
     {"Granatier", "granatier", "/usr/share/icons/hicolor/16x16/apps/granatier.png" },
     {"Hitori", "hitori"},
     {"KAtomic", "katomic -qwindowtitle KAtomic", "/usr/share/icons/hicolor/16x16/apps/katomic.png" },
     {"KBlackBox", "kblackbox -qwindowtitle KBlackBox", "/usr/share/icons/hicolor/16x16/apps/kblackbox.png" },
     {"KBlocks", "kblocks -qwindowtitle KBlocks", "/usr/share/icons/hicolor/16x16/apps/kblocks.png" },
     {"KBounce", "kbounce -qwindowtitle KBounce", "/usr/share/icons/hicolor/16x16/apps/kbounce.png" },
     {"KBreakOut", "kbreakout -qwindowtitle KBreakOut", "/usr/share/icons/hicolor/16x16/apps/kbreakout.png" },
     {"KDiamond", "kdiamond -qwindowtitle KDiamond", "/usr/share/icons/hicolor/16x16/apps/kdiamond.png" },
     {"KFourInLine", "kfourinline", "/usr/share/icons/hicolor/16x16/apps/kfourinline.png" },
     {"KGoldrunner", "kgoldrunner", "/usr/share/icons/hicolor/16x16/apps/kgoldrunner.png" },
     {"KHangMan", "khangman -qwindowtitle \"KHangMan\" ", "/usr/share/icons/hicolor/16x16/apps/khangman.png" },
     {"KJumpingCube", "kjumpingcube -qwindowtitle KJumpingCube", "/usr/share/icons/hicolor/16x16/apps/kjumpingcube.png" },
     {"KMahjongg", "kmahjongg -qwindowtitle KMahjongg", "/usr/share/icons/hicolor/16x16/apps/kmahjongg.png" },
     {"KMines", "kmines -qwindowtitle KMines", "/usr/share/icons/hicolor/16x16/apps/kmines.png" },
     {"KNetWalk", "knetwalk -qwindowtitle KNetWalk", "/usr/share/icons/hicolor/16x16/apps/knetwalk.png" },
     {"KPatience", "kpat -qwindowtitle KPatience ", "/usr/share/icons/hicolor/16x16/apps/kpat.png" },
     {"KReversi", "kreversi -qwindowtitle KReversi", "/usr/share/icons/hicolor/16x16/apps/kreversi.png" },
     {"KSnakeDuel", "ksnakeduel", "/usr/share/icons/hicolor/16x16/apps/ksnakeduel.png" },
     {"KSpaceDuel", "kspaceduel -qwindowtitle KSpaceDuel", "/usr/share/icons/hicolor/16x16/apps/kspaceduel.png" },
     {"KSquares", "ksquares -qwindowicon ksquares -qwindowtitle KSquares", "/usr/share/icons/hicolor/16x16/apps/ksquares.png" },
     {"KSudoku", "ksudoku -qwindowicon ksudoku -qwindowtitle KSudoku", "/usr/share/icons/hicolor/16x16/apps/ksudoku.png" },
     {"Kajongg", "kajongg", "/usr/share/icons/hicolor/16x16/apps/kajongg.png" },
     {"Kanagram", "kanagram", "/usr/share/icons/hicolor/16x16/apps/kanagram.png" },
     {"Kapman", "kapman", "/usr/share/icons/hicolor/16x16/apps/kapman.png" },
     {"Kigo", "kigo  -qwindowicon kigo -qwindowtitle Kigo", "/usr/share/icons/hicolor/16x16/apps/kigo.png" },
     {"Killbots", "killbots -qwindowtitle Killbots", "/usr/share/icons/hicolor/16x16/apps/killbots.png" },
     {"Kiriki", "kiriki -qwindowtitle Kiriki", "/usr/share/icons/hicolor/16x16/apps/kiriki.png" },
     {"Klickety", "klickety -qwindowtitle Klickety", "/usr/share/icons/hicolor/16x16/apps/klickety.png" },
     {"Klotski", "gnome-klotski", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Klotski.png" },
     {"Knights", "knights  -qwindowtitle Knights", "/usr/share/icons/hicolor/16x16/apps/knights.png" },
     {"Kolf", "kolf ", "/usr/share/icons/hicolor/16x16/apps/kolf.png" },
     {"Kollision", "kollision", "/usr/share/icons/hicolor/16x16/apps/kollision.png" },
     {"Kolor Lines", "klines -qwindowtitle Kolor Lines", "/usr/share/icons/hicolor/16x16/apps/klines.png" },
     {"Konquest", "konquest -qwindowtitle Konquest", "/usr/share/icons/hicolor/16x16/apps/konquest.png" },
     {"KsirK", "ksirk -qwindowtitle KsirK -qwindowicon ksirk", "/usr/share/icons/hicolor/16x16/apps/ksirk.png" },
     {"KsirK Skin Editor", "ksirkskineditor -qwindowtitle KsirK Skin Editor -qwindowicon preferences-desktop-locale"},
     {"Kubrick", "kubrick", "/usr/share/icons/hicolor/16x16/apps/kubrick.png" },
     {"LSkat", "lskat", "/usr/share/icons/hicolor/16x16/apps/lskat.png" },
     {"Lights Off", "lightsoff"},
     {"Lutris", "lutris ", "/usr/share/icons/hicolor/16x16/apps/lutris.png" },
     {"Mahjongg", "gnome-mahjongg"},
     {"Minecraft Launcher", "/opt/minecraft-launcher/minecraft-launcher"},
     {"Mines", "gnome-mines"},
     {"Naval Battle", "knavalbattle -qwindowtitle Naval Battle ", "/usr/share/icons/hicolor/16x16/apps/knavalbattle.png" },
     {"Nibbles", "gnome-nibbles", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Nibbles.png" },
     {"Palapeli", "palapeli ", "/usr/share/icons/hicolor/16x16/apps/palapeli.png" },
     {"Potato Guy", "ktuberling -qwindowtitle Potato Guy ", "/usr/share/icons/hicolor/16x16/apps/ktuberling.png" },
     {"Quadrapassel", "quadrapassel"},
     {"Reversi", "iagno", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Reversi.png" },
     {"Robots", "gnome-robots", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Robots.png" },
     {"SameGame", "klickety --KSameMode -qwindowtitle SameGame", "/usr/share/icons/hicolor/16x16/apps/ksame.png" },
     {"Shisen-Sho", "kshisen -qwindowtitle Shisen-Sho", "/usr/share/icons/hicolor/16x16/apps/kshisen.png" },
     {"Sudoku", "gnome-sudoku", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Sudoku.png" },
     {"Swell Foop", "swell-foop", "/usr/share/icons/hicolor/16x16/apps/org.gnome.SwellFoop.png" },
     {"Tali", "tali", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Tali.png" },
     {"Taquin", "gnome-taquin"},
     {"Tetravex", "gnome-tetravex", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Tetravex.png" },
     {"picmi", "picmi", "/usr/share/icons/hicolor/16x16/apps/picmi.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Document Scanner", "simple-scan"},
     {"Document Viewer", "evince "},
     {"Gwenview", "gwenview ", "/usr/share/icons/hicolor/16x16/apps/gwenview.png" },
     {"Image Viewer", "eog "},
     {"KColorChooser", "kcolorchooser", "/usr/share/icons/hicolor/16x16/apps/kcolorchooser.png" },
     {"KRuler", "kruler", "/usr/share/icons/hicolor/16x16/apps/kruler.png" },
     {"Karbon", "karbon ", "/usr/share/icons/hicolor/16x16/apps/calligrakarbon.png" },
     {"KolourPaint", "kolourpaint ", "/usr/share/icons/hicolor/16x16/apps/kolourpaint.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Okular", "okular ", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"XDvi", "xdvi "},
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Akregator", "akregator ", "/usr/share/icons/hicolor/16x16/apps/akregator.png" },
     {"Avahi SSH Server Browser", "/usr/bin/bssh"},
     {"Avahi VNC Server Browser", "/usr/bin/bvnc"},
     {"Chromium", "/usr/bin/chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Contact Print Theme Editor", "contactprintthemeeditor"},
     {"Contact Theme Editor", "contactthemeeditor"},
     {"ELinks", "xterm -e /usr/bin/elinks "},
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"IM Contacts", "ktp-contactlist ", "/usr/share/icons/hicolor/16x16/apps/telepathy-kde.png" },
     {"KDE Connect", "kdeconnect-app"},
     {"KDE Connect Indicator", "kdeconnect-indicator"},
     {"KDE Connect SMS", "kdeconnect-sms"},
     {"KDE IM Log Viewer", "ktp-log-viewer "},
     {"KGet", "kget -qwindowtitle KGet ", "/usr/share/icons/hicolor/16x16/apps/kget.png" },
     {"KMail Header Theme Editor", "headerthemeeditor"},
     {"KRDC", "krdc -qwindowtitle KRDC "},
     {"Konqueror", "konqueror", "/usr/share/icons/hicolor/16x16/apps/konqueror.png" },
     {"Kopete", "kopete -qwindowtitle Kopete ", "/usr/share/icons/hicolor/16x16/apps/kopete.png" },
     {"Krfb", "krfb -qwindowtitle Krfb ", "/usr/share/icons/hicolor/48x48/apps/krfb.png" },
     {"Open on connected device via KDE Connect", "kdeconnect-handler --open "},
     {"PIM Data Exporter", "pimdataexporter", "/usr/share/icons/hicolor/16x16/apps/kontact.png" },
     {"Polari", "gapplication launch org.gnome.Polari "},
     {"Remmina", "remmina-file-wrapper ", "/usr/share/icons/hicolor/16x16/apps/org.remmina.Remmina.png" },
     {"Sieve Editor", "sieveeditor"},
     {"Slack", "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=slack --file-forwarding com.slack.Slack @@u  @@"},
     {"Synology Drive Client", "synology-drive start", "///opt/Synology/SynologyDrive/images/ico_72_cloud_station.png" },
     {"Telegram Desktop", "telegram-desktop -- ", "/usr/share/icons/hicolor/16x16/apps/telegram.png" },
     {"Web", "epiphany "},
     {"Zoom", "/usr/bin/zoom ", "/usr/share/pixmaps/Zoom.png" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Calendar", "gnome-calendar"},
     {"Calligra Gemini", "calligragemini ", "/usr/share/icons/hicolor/16x16/apps/calligragemini.png" },
     {"Calligra Sheets", "calligrasheets ", "/usr/share/icons/hicolor/16x16/apps/calligrasheets.png" },
     {"Calligra Stage", "calligrastage ", "/usr/share/icons/hicolor/16x16/apps/calligrastage.png" },
     {"Calligra Words", "calligrawords ", "/usr/share/icons/hicolor/16x16/apps/calligrawords.png" },
     {"Contact Print Theme Editor", "contactprintthemeeditor"},
     {"Contact Theme Editor", "contactthemeeditor"},
     {"Document Viewer", "evince "},
     {"Evolution", "evolution "},
     {"KMail Header Theme Editor", "headerthemeeditor"},
     {"Karbon", "karbon ", "/usr/share/icons/hicolor/16x16/apps/calligrakarbon.png" },
     {"Kontact", "kontact", "/usr/share/icons/hicolor/16x16/apps/kontact.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Lokalize", "lokalize ", "/usr/share/icons/hicolor/32x32/apps/lokalize.png" },
     {"Okular", "okular ", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Sieve Editor", "sieveeditor"},
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"Accerciser", "accerciser", "/usr/share/icons/hicolor/16x16/apps/accerciser.png" },
     {"Akonadi Console", "akonadiconsole", "/usr/share/icons/hicolor/16x16/apps/akonadiconsole.png" },
     {"Boxes", "gnome-boxes "},
     {"Builder", "gnome-builder "},
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Cervisia", "cervisia -qwindowtitle Cervisia ", "/usr/share/icons/hicolor/16x16/apps/cervisia.png" },
     {"Cuttlefish", "cuttlefish"},
     {"Devhelp", "devhelp"},
     {"GHex", "ghex ", "/usr/share/icons/hicolor/16x16/apps/org.gnome.GHex.png" },
     {"Glade", "glade "},
     {"IntelliJ IDEA Ultimate Edition", "\"/home/box/ide/idea-IU-201.7223.91/bin/idea.sh\" ", "///home/box/ide/idea-IU-201.7223.91/bin/idea.svg" },
     {"Julia", "xterm -e julia"},
     {"KAppTemplate", "kapptemplate", "/usr/share/icons/hicolor/16x16/apps/kapptemplate.png" },
     {"KCachegrind", "kcachegrind -qwindowtitle KCachegrind ", "/usr/share/icons/hicolor/32x32/apps/kcachegrind.png" },
     {"KDevelop", "kdevelop", "/usr/share/icons/hicolor/16x16/apps/kdevelop.png" },
     {"KDevelop (Pick Session)", "kdevelop --ps", "/usr/share/icons/hicolor/16x16/apps/kdevelop.png" },
     {"KDiff3", "kdiff3", "/usr/share/icons/hicolor/16x16/apps/kdiff3.png" },
     {"KImageMapEditor", "kimagemapeditor -qwindowtitle KImageMapEditor  ", "/usr/share/icons/hicolor/16x16/apps/kimagemapeditor.png" },
     {"KUIViewer", "kuiviewer -qwindowtitle KUIViewer ", "/usr/share/icons/hicolor/16x16/apps/kuiviewer.png" },
     {"Kirigami Gallery", "kirigami2gallery"},
     {"Kompare", "kompare -o ", "/usr/share/icons/hicolor/16x16/apps/kompare.png" },
     {"Lokalize", "lokalize ", "/usr/share/icons/hicolor/32x32/apps/lokalize.png" },
     {"Plasma Engine Explorer", "plasmaengineexplorer"},
     {"Plasma Global Theme Explorer", "lookandfeelexplorer"},
     {"Plasma Theme Explorer", "plasmathemeexplorer"},
     {"Qt Assistant", "assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "designer ", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "linguist ", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Sublime Text", "/opt/sublime_text/sublime_text ", "/usr/share/icons/hicolor/16x16/apps/sublime-text.png" },
     {"Sysprof", "sysprof "},
     {"Umbrello", "umbrello5  -caption Umbrello", "/usr/share/icons/hicolor/16x16/apps/umbrello.png" },
     {"UserFeedback Console", "UserFeedbackConsole"},
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
 }

 local menu80d754c83abbbd4ef5d150904efcc86c = {
     {"Julia", "xterm -e julia"},
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Cheese", "cheese"},
     {"Dragon Player", "dragon ", "/usr/share/icons/hicolor/16x16/apps/dragonplayer.png" },
     {"Elisa", "elisa ", "/usr/share/icons/hicolor/16x16/apps/elisa.png" },
     {"JuK", "juk ", "/usr/share/icons/hicolor/16x16/apps/juk.png" },
     {"K3b", "k3b ", "/usr/share/icons/hicolor/16x16/apps/k3b.png" },
     {"Kamoso", "kamoso -qwindowtitle Kamoso", "/usr/share/icons/hicolor/16x16/apps/kamoso.png" },
     {"Kdenlive", "kdenlive ", "/usr/share/icons/hicolor/16x16/apps/kdenlive.png" },
     {"Kwave Sound Editor", "kwave "},
     {"Music", "gnome-music"},
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Qt V4L2 video capture utility", "qvidcap", "/usr/share/icons/hicolor/16x16/apps/qvidcap.png" },
     {"Sound Recorder", "gnome-sound-recorder"},
     {"Spotify", "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=spotify --file-forwarding com.spotify.Client @@u  @@"},
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"Videos", "totem "},
     {"Volume Icon", "volumeicon"},
     {"mpv Media Player", "mpv --player-operation-mode=pseudo-gui -- ", "/usr/share/icons/hicolor/16x16/apps/mpv.png" },
     {"xine", "xine ", "/usr/share/icons/hicolor/16x16/apps/xine.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Alacritty", "alacritty", "/usr/share/pixmaps/Alacritty.svg" },
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover"},
     {"Boxes", "gnome-boxes "},
     {"Color Profile Viewer", "gcm-viewer", "/usr/share/icons/hicolor/16x16/apps/gnome-color-manager.png" },
     {"Discover", "plasma-discover ", "/usr/share/icons/hicolor/16x16/apps/plasmadiscover.png" },
     {"Disk Usage Analyzer", "baobab"},
     {"Dolphin", "dolphin "},
     {"Hardware Locality lstopo", "lstopo"},
     {"KDiskFree", "kdf -qwindowtitle KDiskFree", "/usr/share/icons/hicolor/16x16/apps/kdf.png" },
     {"KSysGuard", "ksysguard "},
     {"KSystemLog", "/usr/bin/kdesu ksystemlog -qwindowtitle KSystemLog"},
     {"KWalletManager", "kwalletmanager5 ", "/usr/share/icons/hicolor/16x16/apps/kwalletmanager.png" },
     {"Konsole", "konsole"},
     {"KwikDisk", "kwikdisk -qwindowtitle KwikDisk", "/usr/share/icons/hicolor/16x16/apps/kwikdisk.png" },
     {"Logs", "gnome-logs"},
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"MultiWriter", "gnome-multi-writer", "/usr/share/icons/hicolor/16x16/apps/org.gnome.MultiWriter.png" },
     {"Network Tools", "gnome-nettool", "/usr/share/icons/hicolor/16x16/apps/gnome-nettool.png" },
     {"OpenJDK Java 11 Console", "/usr/lib/jvm/java-11-openjdk/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/java11-openjdk.png" },
     {"OpenJDK Java 11 Shell", "xterm -e /usr/lib/jvm/java-11-openjdk/bin/jshell", "/usr/share/icons/hicolor/16x16/apps/java11-openjdk.png" },
     {"Parental Controls", "malcontent-control"},
     {"Software", "gnome-software "},
     {"System Monitor", "gnome-system-monitor"},
     {"Terminal", "gnome-terminal"},
     {"Terminator", "terminator", "/usr/share/icons/hicolor/16x16/apps/terminator.png" },
     {"Termite", "termite"},
     {"Usage", "gnome-usage"},
     {"Yakuake", "yakuake", "/usr/share/icons/hicolor/16x16/apps/yakuake.png" },
     {"conky", "conky --daemonize --pause=1"},
     {"dconf Editor", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/ca.desrt.dconf-editor.png" },
     {"kitty", "kitty", "/usr/share/icons/hicolor/256x256/apps/kitty.png" },
     {"ranger", "xterm -e ranger"},
     {"urxvt", "urxvt"},
     {"urxvt (client)", "urxvtc"},
     {"urxvt (tabbed)", "urxvt-tabbed"},
 }

xdgmenu = {
    {"Accessibility", menue0e4fc6213e8b3593495a7260c3a4c2e},
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Science & Math", menu80d754c83abbbd4ef5d150904efcc86c},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

